<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->tag->gettitle(); ?>
        <?php $this->assets->outputCss()?>		
    </head>
    <body>

       <?php echo $this->getContent(); ?>
       
    </body>
    <?php $this->assets->outputJs() ?>
</html>
