<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">H+</h1>

            </div>
            <h3>欢迎使用 H+</h3>

            <form class="m-t" role="form" action="index.html">
            <?php echo $this->tag->form(array('frontend/login/login','method'=>'post','class'=>'m-t','role'=>"form"));?>
                <div class="form-group">
                    <?php echo $this->tag->textField(array("nick","class"=>"form-control","placeholder"=>"用户名"))?>
                </div>
                <div class="form-group">
                    <?php echo $this->tag->passwordField(array("passwd","class"=>"form-control","placeholder"=>"密码"));?>
                    
                </div>
                <?php echo $this->tag->submitButton(array("登陆","class"=>"btn btn-primary block full-width m-b"))?>
                

                <p class="text-muted text-center"> <a href="login.html#"><small>忘记密码了？</small></a> | <?php echo $this->tag->linkTo('/frontend/login/register', '注册'); ?>
                </p>

            </form>
        </div>
    </div>
</body>