<form action='<?php echo $this->url->get('/frontend/user/login');?>' method='post'>
    <label for='nick'>用户名<input type='text' name='nick' placeholder='请输入用户名'></label>
    <label for='nick'>&nbsp;密码<input type='password' name='passwd' placeholder='请输入密码'></label>
    <input type='submit' value='登陆'>
    <?php echo $this->tag->linkTo(array('/frontend/user/register', '注册', 'class' => 'edit-btn')); ?>
</form>