<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">H+</h1>

            </div>
            <h3>欢迎注册 H+</h3>
            <p>创建一个H+新账户</p>
            <?php echo $this->tag->form(array('frontend/login/login','method'=>'post','class'=>'m-t','role'=>"form"));?>
            
                <div class="form-group">
                    <?php echo $this->tag->passwordField(array("passwd","class"=>"form-control","placeholder"=>"请输入密码"));?>                    
                </div>
                <div class="form-group">
                    <?php echo $this->tag->passwordField(array("repasswd","class"=>"form-control","placeholder"=>"请再次输入密码"));?>                    
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="请再次输入密码" required="">
                </div>
                <div class="form-group text-left">
                    <div class="checkbox i-checks">
                        <label class="no-padding">
                            <?php echo $this->tag->checkField(array('argeement','value'=>'y'))?><i></i> 我同意注册协议
                         </label>
                            
                    </div>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">注 册</button>

                <p class="text-muted text-center"><small>已经有账户了？</small>
                <?php echo $this->tag->linkTo('/frontend/login/login', '点此登录'); ?>
                
                </p>

            </form>
        </div>
    </div>
    <script>
        $(document).ready(function(){$(".i-checks").iCheck({checkboxClass:"icheckbox_square-green",radioClass:"iradio_square-green",})});
    </script>

</body>
