<div class="row">
	<div class="col-sm-12">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>
					所有表单元素 <small>包括自定义样式的复选和单选按钮</small>
				</h5>

			</div>
			<div class="ibox-content">
				<form method="post" action="<?php echo $this->url->get("/frontend/tools/add");?>" class="form-horizontal">
					<input type="hidden" name="pid" value="<?php echo $pid;?>" />
					<div class="form-group">
						<label class="col-sm-2 control-label">方法名</label>

						<div class="col-sm-3">
							<input type="text" name="method" class="form-control" placeholder="请输入控制器名">
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<div class="form-group">
						<label class="col-sm-2 control-label">别名</label>

						<div class="col-sm-3">
							<input type="text" name="alias" class="form-control" placeholder="请输入控制器别名">
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<div class="form-group">
						<label class="col-sm-2 control-label"></label>

						<div class="col-sm-10">
							<label class="checkbox-inline i-checks">
								<div class="icheckbox_square-green" style="position: relative;">
									<input type="checkbox" value="0"
										style="position: absolute; opacity: 0;">
									<ins class="iCheck-helper"
										style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
								</div>是否显示
							</label>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<div class="form-group">
						<div class="col-sm-4 col-sm-offset-2">
							<button class="btn btn-primary" type="submit">保存内容</button>
							<button class="btn btn-white" type="submit">取消</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>